// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/google/wire"
	"week04.homework.szs/internal/biz"
	"week04.homework.szs/internal/data"
	"week04.homework.szs/internal/service"
)

// Injectors from wire.go:

func InitializeArticle() *service.ArticleSvc {
	mockArticleRepo := data.NewMockArticleRepo()
	articleSvc := service.NewArticleSvc(mockArticleRepo)
	return articleSvc
}

// wire.go:

var ArticleRepoSet = wire.NewSet(data.NewMockArticleRepo, wire.Bind(new(biz.ArticleRepo), new(*data.MockArticleRepo)))
